sources:
  - xproj/
templates:
  - xproj/Template/AutoEquatable.stencil
  - xproj/Template/AutoHashable.stencil
  - xproj/Template/AutoMockable.stencil
  - xproj/Template/PBXType.stencil
output:
  xproj/SourceTemplates.swift